/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_keenon_loglinear_fastmath_FastMath */

#ifndef _Included_com_github_keenon_loglinear_fastmath_FastMath
#define _Included_com_github_keenon_loglinear_fastmath_FastMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_keenon_loglinear_fastmath_FastMath
 * Method:    native_log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_keenon_loglinear_fastmath_FastMath_native_1log
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_github_keenon_loglinear_fastmath_FastMath
 * Method:    native_exp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_keenon_loglinear_fastmath_FastMath_native_1exp
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
